package rustgen

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/cachegen"
	"github.com/Lumos-Labs-HQ/flash/internal/config"
	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
	"github.com/Lumos-Labs-HQ/flash/internal/utils"
)

type Generator struct {
	Config       *config.Config
	schema       *parser.Schema
	schemaParser *parser.SchemaParser
	queryParser  *parser.QueryParser
	cache        *gencommon.GenerationCache
	expander     *gencommon.SchemaExpander
	caches       []*cachegen.CacheInfo // resolved @cache annotations
}

func New(cfg *config.Config) *Generator {
	cache := gencommon.NewGenerationCacheWithDir(cfg.Gen.Rust.Out)
	return &Generator{
		Config:       cfg,
		schemaParser: parser.NewSchemaParser(cfg),
		queryParser:  parser.NewQueryParser(cfg),
		cache:        cache,
	}
}

func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.Config.Gen.Rust.Out, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	schema, err := g.schemaParser.Parse()
	if err != nil {
		return fmt.Errorf("failed to parse schema: %w", err)
	}
	g.schema = schema
	g.expander = gencommon.NewSchemaExpander(schema)

	schemaHash, _ := g.cache.ComputeSchemaChecksum(g.Config.SchemaDir)
	configHash := g.computeConfigChecksum()
	fullRegen := g.Config.ForceRegen || g.cache.ShouldRegenerateAll(schemaHash, configHash)

	queries, err := g.queryParser.Parse(schema)
	if err != nil {
		return fmt.Errorf("failed to parse queries: %w", err)
	}

	if fullRegen || g.cache.SchemaChecksum != schemaHash {
		if err := g.generateModels(); err != nil {
			return err
		}
		if err := g.generateDB(queries); err != nil {
			return err
		}
	}

	if err := g.generateQueriesIncremental(queries, fullRegen); err != nil {
		return err
	}

	// Generate cache layer if enabled
	if g.Config.Cache.Enabled {
		// Resolve cache annotations and store for query wrapping
		g.caches = cachegen.ResolveCacheQueries(queries, &g.Config.Cache)

		// Validate dep references
		if warnings := cachegen.ValidateDeps(g.caches, queries); len(warnings) > 0 {
			for _, w := range warnings {
				fmt.Printf("⚠️  %s\n", w)
			}
		}

		if err := g.generateCache(queries); err != nil {
			return err
		}
	}

	if err := g.generateModRS(queries); err != nil {
		return err
	}
	if err := g.generateMigrations(); err != nil {
		return err
	}

	g.cache.UpdateSchemaChecksum(schemaHash)
	g.cache.UpdateConfigChecksum(configHash)
	g.cache.MarkGeneration()
	_ = g.cache.Save()
	return nil
}

func (g *Generator) computeConfigChecksum() string {
	configStr := fmt.Sprintf("%s|%s|%s|%s|%v",
		g.Config.SchemaDir,
		g.Config.Queries,
		g.Config.Database.Provider,
		g.Config.Gen.Rust.Driver,
		g.Config.Gen.Rust.Macros,
	)
	hash := sha256.Sum256([]byte(configStr))
	return fmt.Sprintf("%x", hash)
}

// generateModRS creates the mod.rs file that re-exports all generated modules
func (g *Generator) generateModRS(queries []*parser.Query) error {
	var w strings.Builder

	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
	w.WriteString("pub mod models;\n")
	w.WriteString("pub mod db;\n")
	// Only expose migrations when migration files are present. Projects that use
	// Flash solely for query generation should not be forced to compile an
	// embedded migration runner.
	if migrationsExist(g.Config.MigrationsPath) {
		w.WriteString("pub mod migrations;\n")
	}

	// Cache modules
	if g.Config.Cache.Enabled {
		w.WriteString("pub mod cache;\n")
		w.WriteString("pub mod cache_accessors;\n")
		w.WriteString("pub mod cached_queries;\n")
	}

	// Collect unique source file modules
	seen := make(map[string]bool)
	for _, q := range queries {
		modName := toRustModuleName(q.SourceFile)
		if !seen[modName] {
			seen[modName] = true
			w.WriteString(fmt.Sprintf("pub mod %s;\n", modName))
		}
	}

	outPath := filepath.Join(g.Config.Gen.Rust.Out, "mod.rs")
	return os.WriteFile(outPath, []byte(w.String()), 0644)
}

func migrationsExist(path string) bool {
	if path == "" {
		return false
	}
	if entries, err := os.ReadDir(path); err == nil {
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".sql") {
				return true
			}
		}
	}
	return false
}

func (g *Generator) generateModels() error {
	var w strings.Builder
	w.Grow(200 + len(g.schema.Tables)*200)

	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n")
	w.WriteString("#![allow(dead_code)]\n\n")

	// Collect imports needed
	needsChronoNaive := false
	needsChronoUtc := false
	needsUUID := false
	needsDecimal := false
	needsSerde := true // always for JSON serialization
	needsJsonValue := false

	for _, t := range g.schema.Tables {
		for _, c := range t.Columns {
			rustType := g.sqlTypeToRust(c.Type, false)
			if strings.Contains(rustType, "NaiveDateTime") {
				needsChronoNaive = true
			}
			if strings.Contains(rustType, "DateTime<Utc>") {
				needsChronoUtc = true
			}
			if strings.Contains(rustType, "Uuid") {
				needsUUID = true
			}
			if strings.Contains(rustType, "Decimal") || strings.Contains(rustType, "BigDecimal") {
				needsDecimal = true
			}
			if strings.Contains(rustType, "serde_json::Value") {
				needsJsonValue = true
			}
		}
	}

	// Write imports
	if needsSerde {
		w.WriteString("use serde::{Deserialize, Serialize};\n")
	}
	if needsChronoNaive || needsChronoUtc {
		imports := []string{}
		if needsChronoNaive {
			imports = append(imports, "NaiveDateTime")
		}
		if needsChronoUtc {
			imports = append(imports, "DateTime", "Utc")
		}
		w.WriteString(fmt.Sprintf("use chrono::{%s};\n", strings.Join(imports, ", ")))
	}
	if needsUUID {
		w.WriteString("use uuid::Uuid;\n")
	}
	if needsDecimal {
		w.WriteString("use rust_decimal::Decimal;\n")
	}
	if needsJsonValue {
		w.WriteString("use serde_json::Value;\n")
	}
	w.WriteString("use sqlx::FromRow;\n")
	w.WriteString("\n")

	// Generate enums
	for _, enum := range g.schema.Enums {
		enumName := utils.ToPascalCase(enum.Name)
		w.WriteString("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]\n")
		w.WriteString(fmt.Sprintf("#[sqlx(type_name = \"%s\", rename_all = \"snake_case\")]\n", enum.Name))
		w.WriteString(fmt.Sprintf("pub enum %s {\n", enumName))
		for _, val := range enum.Values {
			variantName := utils.ToPascalCase(val)
			w.WriteString(fmt.Sprintf("    #[sqlx(rename = \"%s\")]\n", val))
			w.WriteString(fmt.Sprintf("    %s,\n", variantName))
		}
		w.WriteString("}\n\n")
	}

	// Generate table structs
	for _, table := range g.schema.Tables {
		structName := utils.ToPascalCase(table.Name)
		w.WriteString("#[derive(Debug, Clone, FromRow, Serialize, Deserialize)]\n")
		w.WriteString(fmt.Sprintf("pub struct %s {\n", structName))
		for _, col := range table.Columns {
			fieldName := utils.ToSnakeCase(col.Name)
			rustType := g.sqlTypeToRust(col.Type, col.Nullable)
			w.WriteString(fmt.Sprintf("    pub %s: %s,\n", fieldName, rustType))
		}
		w.WriteString("}\n\n")
	}

	outPath := filepath.Join(g.Config.Gen.Rust.Out, "models.rs")
	return os.WriteFile(outPath, []byte(w.String()), 0644)
}

func (g *Generator) generateDB(queries []*parser.Query) error {
	var w strings.Builder

	poolType := g.getPoolType()
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n")
	w.WriteString("#![allow(dead_code)]\n\n")

	w.WriteString("/// Database connection wrapper for FlashORM queries.\n")
	w.WriteString(fmt.Sprintf("pub struct Queries {\n    pub(crate) pool: %s,\n}\n\n", poolType))
	w.WriteString(fmt.Sprintf("impl Queries {\n    pub fn new(pool: %s) -> Self {\n        Self { pool }\n    }\n}\n", poolType))

	outPath := filepath.Join(g.Config.Gen.Rust.Out, "db.rs")
	return os.WriteFile(outPath, []byte(w.String()), 0644)
}

func (g *Generator) generateCache(queries []*parser.Query) error {
	// Generate cache.rs — the FlashCache struct with Redis connection
	cacheCode := cachegen.GenerateRustCache(&g.Config.Cache)
	cachePath := filepath.Join(g.Config.Gen.Rust.Out, "cache.rs")
	if err := os.WriteFile(cachePath, []byte(cacheCode), 0644); err != nil {
		return fmt.Errorf("failed to write cache.rs: %w", err)
	}

	// Resolve cache annotations from queries
	caches := cachegen.ResolveCacheQueries(queries, &g.Config.Cache)

	// Generate cache_accessors.rs — named cache accessor structs
	accessorCode := cachegen.GenerateRustCacheAccessors(caches)
	if accessorCode == "" {
		accessorCode = "// Code generated by FlashORM. DO NOT EDIT.\n// No @cache annotations found.\n"
	}
	accessorPath := filepath.Join(g.Config.Gen.Rust.Out, "cache_accessors.rs")
	if err := os.WriteFile(accessorPath, []byte(accessorCode), 0644); err != nil {
		return fmt.Errorf("failed to write cache_accessors.rs: %w", err)
	}

	// Generate cached_queries.rs — cache-wrapped query methods + auto-purge mutations
	cachedCode := g.generateCachedQueries(queries, caches)
	cachedPath := filepath.Join(g.Config.Gen.Rust.Out, "cached_queries.rs")
	if err := os.WriteFile(cachedPath, []byte(cachedCode), 0644); err != nil {
		return fmt.Errorf("failed to write cached_queries.rs: %w", err)
	}

	return nil
}

// generateCachedQueries produces cache-wrapped query methods and auto-purge mutation wrappers
func (g *Generator) generateCachedQueries(queries []*parser.Query, caches []*cachegen.CacheInfo) string {
	var w strings.Builder

	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n")
	w.WriteString("#![allow(unused_imports, dead_code)]\n\n")
	w.WriteString("use super::cache::CACHE;\n")
	w.WriteString("use super::cache_accessors::*;\n")
	w.WriteString("use super::db::Queries;\n")
	w.WriteString("use super::models::*;\n")
	w.WriteString("use serde::{Serialize, de::DeserializeOwned};\n")
	w.WriteString("use std::time::Duration;\n\n")

	w.WriteString("/// Cached query wrapper — provides cache-first access to database queries.\n")
	w.WriteString("/// Falls back to database on cache miss, then stores the result.\n")
	w.WriteString("impl Queries {\n")

	for _, q := range queries {
		cmd := strings.ToLower(q.Cmd)

		if cachegen.IsCachedQuery(q) && !cachegen.IsMutationQuery(q) {
			// Phase 4: Cache-wrapped query method
			g.writeCachedQueryMethod(&w, q, caches)
		} else if cachegen.IsMutationQuery(q) {
			// Phase 5: Auto-purge mutation wrapper
			purges := cachegen.ResolveDependencyPurges(q.Name, caches, q.Params)
			if len(purges) > 0 {
				g.writePurgingMutationMethod(&w, q, purges)
			}
			_ = cmd
		}
	}

	w.WriteString("}\n")
	return w.String()
}

// writeCachedQueryMethod generates a cache-first wrapper for a cached query
func (g *Generator) writeCachedQueryMethod(w *strings.Builder, q *parser.Query, caches []*cachegen.CacheInfo) {
	cacheInfo := cachegen.GetCacheInfoForQuery(q.Name, caches)
	if cacheInfo == nil {
		return
	}

	fnName := toRustFnName(q.Name) + "_cached"
	columns := g.expandWildcardColumns(q)
	cmd := strings.ToLower(q.Cmd)

	// Determine return type
	var returnType string
	switch cmd {
	case ":one", "one":
		returnType = g.getOneReturnType(q, columns)
	case ":many", "many":
		returnType = fmt.Sprintf("Vec<%s>", g.getOneReturnType(q, columns))
	default:
		return // only cache :one and :many
	}

	// Build params
	w.WriteString(fmt.Sprintf("    /// %s (cached, TTL: %s)\n", q.Name, cacheInfo.TTL))
	w.WriteString(fmt.Sprintf("    pub async fn %s(\n        &self,\n", fnName))

	var paramNames []string
	if len(q.Params) > 2 {
		paramsStruct := toRustStructName(q.Name) + "Params"
		w.WriteString(fmt.Sprintf("        params: &%s,\n", paramsStruct))
		for _, p := range q.Params {
			paramNames = append(paramNames, fmt.Sprintf("params.%s", utils.ToSnakeCase(p.Name)))
		}
	} else {
		for _, p := range q.Params {
			paramName := utils.ToSnakeCase(p.Name)
			paramType := g.paramTypeToRustNullable(p.Type, p.Nullable)
			w.WriteString(fmt.Sprintf("        %s: %s,\n", paramName, paramType))
			paramNames = append(paramNames, paramName)
		}
	}

	w.WriteString(fmt.Sprintf("    ) -> Result<%s, sqlx::Error> {\n", returnType))

	// Build cache key
	var keyExpr string
	if len(paramNames) == 0 {
		keyExpr = fmt.Sprintf("\"%s\"", cacheInfo.CacheName)
	} else {
		formatParts := make([]string, len(paramNames))
		for i := range paramNames {
			formatParts[i] = "{}"
		}
		keyExpr = fmt.Sprintf("format!(\"%s:%s\", %s)", cacheInfo.CacheName, strings.Join(formatParts, ":"), strings.Join(paramNames, ", "))
	}
	w.WriteString(fmt.Sprintf("        let cache_key = %s;\n\n", keyExpr))

	// Check cache first
	w.WriteString("        // Check cache first\n")
	w.WriteString(fmt.Sprintf("        if let Some(cached) = CACHE.get::<%s>(&cache_key) {\n", returnType))
	w.WriteString("            return Ok(cached);\n")
	w.WriteString("        }\n\n")

	// Call the real query method
	w.WriteString("        // Cache miss — query database\n")
	var callArgs string
	if len(q.Params) > 2 {
		callArgs = "params"
	} else {
		callArgs = strings.Join(paramNames, ", ")
	}
	w.WriteString(fmt.Sprintf("        let result = self.%s(%s).await?;\n\n", toRustFnName(q.Name), callArgs))

	// Store in cache
	ttlSec := cachegen.ParseTTL(cacheInfo.TTL)
	tagsLiteral := "&[]"
	if len(cacheInfo.Tags) > 0 {
		quoted := make([]string, len(cacheInfo.Tags))
		for i, t := range cacheInfo.Tags {
			quoted[i] = fmt.Sprintf(`"%s"`, t)
		}
		tagsLiteral = fmt.Sprintf("&[%s]", strings.Join(quoted, ", "))
	}
	w.WriteString(fmt.Sprintf("        // Store in cache (TTL: %s)\n", cacheInfo.TTL))
	w.WriteString(fmt.Sprintf("        CACHE.set(&cache_key, &result, Duration::from_secs(%d), %s);\n\n", ttlSec, tagsLiteral))
	w.WriteString("        Ok(result)\n")
	w.WriteString("    }\n\n")
}

// writePurgingMutationMethod generates a mutation wrapper that auto-purges dependent caches
func (g *Generator) writePurgingMutationMethod(w *strings.Builder, q *parser.Query, purges []cachegen.DependencyPurge) {
	fnName := toRustFnName(q.Name) + "_and_purge"
	cmd := strings.ToLower(q.Cmd)

	// Determine return type
	var returnType string
	switch cmd {
	case ":exec", "exec":
		returnType = "()"
	case ":execresult", "execresult":
		returnType = g.getExecResultType()
	default:
		returnType = "()"
	}

	// Build function signature
	w.WriteString(fmt.Sprintf("    /// %s (auto-purges dependent caches)\n", q.Name))
	w.WriteString(fmt.Sprintf("    pub async fn %s(\n        &self,\n", fnName))

	var paramNames []string
	if len(q.Params) > 2 {
		paramsStruct := toRustStructName(q.Name) + "Params"
		w.WriteString(fmt.Sprintf("        params: &%s,\n", paramsStruct))
		for _, p := range q.Params {
			paramNames = append(paramNames, fmt.Sprintf("params.%s", utils.ToSnakeCase(p.Name)))
		}
	} else {
		for _, p := range q.Params {
			paramName := utils.ToSnakeCase(p.Name)
			paramType := g.paramTypeToRustNullable(p.Type, p.Nullable)
			w.WriteString(fmt.Sprintf("        %s: %s,\n", paramName, paramType))
			paramNames = append(paramNames, paramName)
		}
	}

	w.WriteString(fmt.Sprintf("    ) -> Result<%s, sqlx::Error> {\n", returnType))

	// Call the real mutation
	var callArgs string
	if len(q.Params) > 2 {
		callArgs = "params"
	} else {
		callArgs = strings.Join(paramNames, ", ")
	}
	w.WriteString(fmt.Sprintf("        let result = self.%s(%s).await?;\n\n", toRustFnName(q.Name), callArgs))

	// Inject purge calls
	w.WriteString("        // Auto-purge dependent caches\n")
	for _, purge := range purges {
		if purge.PurgePrefix {
			w.WriteString(fmt.Sprintf("        CACHE.purge_by_prefix(\"%s:\");\n", purge.CacheName))
		} else {
			paramRef := utils.ToSnakeCase(purge.KeyParam)
			// Check if it's from params struct
			for _, pn := range paramNames {
				if strings.HasSuffix(pn, "."+paramRef) {
					paramRef = pn
					break
				}
			}
			w.WriteString(fmt.Sprintf("        CACHE.del(&format!(\"%s:{}\", %s));\n", purge.CacheName, paramRef))
		}
	}

	w.WriteString("\n        Ok(result)\n")
	w.WriteString("    }\n\n")
}

func (g *Generator) getPoolType() string {
	switch g.Config.Database.Provider {
	case "mysql":
		return "sqlx::MySqlPool"
	case "sqlite":
		return "sqlx::SqlitePool"
	default:
		return "sqlx::PgPool"
	}
}

func (g *Generator) getDBType() string {
	switch g.Config.Database.Provider {
	case "mysql":
		return "sqlx::MySql"
	case "sqlite":
		return "sqlx::Sqlite"
	default:
		return "sqlx::Postgres"
	}
}

// sqlTypeToRust maps SQL types to Rust types (for sqlx)
func (g *Generator) sqlTypeToRust(sqlType string, nullable bool) string {
	upper := strings.ToUpper(strings.TrimSpace(sqlType))

	// Handle arrays
	if strings.HasSuffix(upper, "[]") {
		inner := sqlType[:len(sqlType)-2]
		innerType := g.sqlTypeToRust(inner, false)
		t := fmt.Sprintf("Vec<%s>", innerType)
		if nullable {
			return fmt.Sprintf("Option<%s>", t)
		}
		return t
	}

	// Check for schema enums
	for _, enum := range g.schema.Enums {
		if strings.EqualFold(enum.Name, sqlType) {
			t := utils.ToPascalCase(enum.Name)
			if nullable {
				return fmt.Sprintf("Option<%s>", t)
			}
			return t
		}
	}

	var t string
	switch {
	// Integer types
	case upper == "SMALLINT" || upper == "INT2" || upper == "SMALLSERIAL":
		t = "i16"
	case upper == "INTEGER" || upper == "INT" || upper == "INT4" || upper == "SERIAL":
		// SQLite stores every INTEGER value as a signed 64-bit integer. Mapping
		// it to i32 makes generated models incompatible with sqlx's native SQLite
		// representation and with rowid/primary-key values.
		if strings.EqualFold(g.Config.Database.Provider, "sqlite") {
			t = "i64"
		} else {
			t = "i32"
		}
	case upper == "BIGINT" || upper == "INT8" || upper == "BIGSERIAL":
		t = "i64"

	// Float types
	case upper == "REAL" || upper == "FLOAT4" || upper == "FLOAT":
		t = "f32"
	case upper == "DOUBLE PRECISION" || upper == "FLOAT8" || upper == "DOUBLE":
		t = "f64"
	case upper == "NUMERIC" || upper == "DECIMAL" || strings.HasPrefix(upper, "NUMERIC(") || strings.HasPrefix(upper, "DECIMAL("):
		t = "Decimal"

	// Boolean
	case upper == "BOOLEAN" || upper == "BOOL":
		t = "bool"

	// String types
	case upper == "TEXT" || upper == "CITEXT" || upper == "NAME":
		t = "String"
	case strings.HasPrefix(upper, "VARCHAR") || strings.HasPrefix(upper, "CHAR") || strings.HasPrefix(upper, "CHARACTER"):
		t = "String"

	// UUID
	case upper == "UUID":
		t = "Uuid"

	// Date/time
	case upper == "DATE":
		t = "chrono::NaiveDate"
	case upper == "TIME" || upper == "TIME WITHOUT TIME ZONE":
		t = "chrono::NaiveTime"
	case upper == "TIMESTAMP" || upper == "TIMESTAMP WITHOUT TIME ZONE" || upper == "DATETIME":
		t = "NaiveDateTime"
	case upper == "TIMESTAMPTZ" || upper == "TIMESTAMP WITH TIME ZONE":
		t = "DateTime<Utc>"

	// Binary
	case upper == "BYTEA" || upper == "BLOB" || strings.HasPrefix(upper, "BINARY") || strings.HasPrefix(upper, "VARBINARY"):
		t = "Vec<u8>"

	// JSON
	case upper == "JSON" || upper == "JSONB":
		t = "serde_json::Value"

	// ─── PostgreSQL Extension Types ───────────────────────────────────────

	// pgvector — vector similarity search
	case upper == "VECTOR" || strings.HasPrefix(upper, "VECTOR("):
		t = "pgvector::Vector"
	case upper == "HALFVEC" || strings.HasPrefix(upper, "HALFVEC("):
		t = "pgvector::HalfVec"
	case upper == "SPARSEVEC" || strings.HasPrefix(upper, "SPARSEVEC("):
		t = "pgvector::SparseVec"

	// Interval
	case upper == "INTERVAL":
		t = "sqlx::postgres::types::PgInterval"

	// Bit types
	case upper == "BIT" || strings.HasPrefix(upper, "BIT(") ||
		upper == "VARBIT" || strings.HasPrefix(upper, "VARBIT(") || strings.HasPrefix(upper, "BIT VARYING"):
		t = "sqlx::postgres::types::PgBitVec"

	// Network types
	case upper == "INET" || upper == "CIDR":
		t = "ipnetwork::IpNetwork"
	case upper == "MACADDR" || upper == "MACADDR8":
		t = "mac_address::MacAddress"

	// PostGIS — geometry/geography
	case upper == "GEOMETRY" || strings.HasPrefix(upper, "GEOMETRY(") ||
		upper == "GEOGRAPHY" || strings.HasPrefix(upper, "GEOGRAPHY("):
		t = "geo_types::Geometry<f64>"

	// PostgreSQL geometric types (built-in)
	case upper == "POINT":
		t = "sqlx::postgres::types::PgPoint"
	case upper == "LINE" || upper == "LSEG" || upper == "BOX" ||
		upper == "PATH" || upper == "POLYGON" || upper == "CIRCLE":
		t = "String"

	// Full-text search
	case upper == "TSVECTOR" || upper == "TSQUERY":
		t = "String"

	// Range types
	case upper == "INT4RANGE" || upper == "INT4MULTIRANGE":
		t = "sqlx::postgres::types::PgRange<i32>"
	case upper == "INT8RANGE" || upper == "INT8MULTIRANGE":
		t = "sqlx::postgres::types::PgRange<i64>"
	case upper == "NUMRANGE" || upper == "NUMMULTIRANGE":
		t = "sqlx::postgres::types::PgRange<Decimal>"
	case upper == "TSRANGE" || upper == "TSMULTIRANGE":
		t = "sqlx::postgres::types::PgRange<NaiveDateTime>"
	case upper == "TSTZRANGE" || upper == "TSTZMULTIRANGE":
		t = "sqlx::postgres::types::PgRange<DateTime<Utc>>"
	case upper == "DATERANGE" || upper == "DATEMULTIRANGE":
		t = "sqlx::postgres::types::PgRange<chrono::NaiveDate>"

	// hstore — key-value pairs
	case upper == "HSTORE":
		t = "sqlx::postgres::types::PgHstore"

	// ltree — hierarchical labels
	case upper == "LTREE" || upper == "LQUERY" || upper == "LTXTQUERY":
		t = "sqlx::postgres::types::PgLTree"

	// Money
	case upper == "MONEY":
		t = "sqlx::postgres::types::PgMoney"

	// OID
	case upper == "OID":
		t = "u32"

	// XML
	case upper == "XML":
		t = "String"

	// pg_lsn — Log Sequence Number
	case upper == "PG_LSN":
		t = "sqlx::postgres::types::PgLsn"

	default:
		t = "String" // fallback
	}

	if nullable {
		return fmt.Sprintf("Option<%s>", t)
	}
	return t
}

// toRustModuleName converts a query source filename to a Rust module name
func toRustModuleName(sourceFile string) string {
	base := filepath.Base(sourceFile)
	name := strings.TrimSuffix(base, filepath.Ext(base))
	return utils.ToSnakeCase(name)
}

// toRustFnName converts a query name to a Rust function name (snake_case)
func toRustFnName(name string) string {
	return utils.ToSnakeCase(name)
}

// toRustStructName converts a query name to a Rust struct name (PascalCase).
// Query names from SQL annotations are already PascalCase (e.g. GetUserAgeStats),
// so we only run ToPascalCase if the name contains separators like underscores.
func toRustStructName(name string) string {
	if strings.ContainsAny(name, "_- .") {
		return utils.ToPascalCase(name)
	}
	// Already PascalCase — just ensure first letter is uppercase
	if len(name) == 0 {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}
