package rustgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
)

func (g *Generator) generateMigrations() error {
	migrations, err := gencommon.LoadEmbeddedMigrations(g.Config.MigrationsPath)
	if err != nil {
		return fmt.Errorf("load migrations for Rust generation: %w", err)
	}
	var w strings.Builder
	w.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\nuse sqlx::Row;\n\n")
	w.WriteString("struct EmbeddedMigration { id: &'static str, name: &'static str, checksum: &'static str, statements: &'static [&'static str] }\n\nstatic MIGRATIONS: &[EmbeddedMigration] = &[\n")
	for _, m := range migrations {
		w.WriteString(fmt.Sprintf("    EmbeddedMigration { id: %s, name: %s, checksum: %s, statements: &[", strconv.Quote(m.ID), strconv.Quote(m.Name), strconv.Quote(m.Checksum)))
		for i, s := range m.Statements {
			if i > 0 {
				w.WriteString(", ")
			}
			w.WriteString(strconv.Quote(s))
		}
		w.WriteString("] },\n")
	}
	w.WriteString("];\n\n")
	w.WriteString("/// Applies embedded migrations using the supplied sqlx pool. No Flash binary is required.\n")
	w.WriteString(fmt.Sprintf("pub async fn FlashInitMigrate(pool: &%s) -> Result<(), sqlx::Error> {\n", g.getPoolType()))
	w.WriteString("    sqlx::query(\"CREATE TABLE IF NOT EXISTS _flash_migrations (id VARCHAR(255) PRIMARY KEY, checksum VARCHAR(64) NOT NULL, finished_at TIMESTAMP NULL, migration_name VARCHAR(255) NOT NULL, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)\").execute(pool).await?;\n")
	w.WriteString("    for migration in MIGRATIONS {\n        let row = sqlx::query(\"SELECT checksum FROM _flash_migrations WHERE id = $1\").bind(migration.id).fetch_optional(pool).await?;\n        if let Some(row) = row { let checksum: String = row.try_get(\"checksum\")?; if checksum != migration.checksum { return Err(sqlx::Error::Protocol(format!(\"applied migration {} checksum mismatch\", migration.id).into())); } continue; }\n        let mut tx = pool.begin().await?;\n        for statement in migration.statements { sqlx::query(*statement).execute(&mut *tx).await?; }\n        sqlx::query(\"INSERT INTO _flash_migrations (id, migration_name, checksum, started_at, finished_at) VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)\").bind(migration.id).bind(migration.name).bind(migration.checksum).execute(&mut *tx).await?;\n        tx.commit().await?;\n    }\n    Ok(())\n}\n")
	return os.WriteFile(filepath.Join(g.Config.Gen.Rust.Out, "migrations.rs"), []byte(w.String()), 0644)
}
